apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend
        image: datnxdevops/knative-frontend:latest
        imagePullPolicy: Always 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  selector:
    app: frontend-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend-service-lb
# spec:
#   type: LoadBalancer
#   selector:
#     app: frontend-service
#   ports:
#   - name: http
#     protocol: TCP
#     port: 80
#     targetPort: 80
