apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        serving.knative.dev/rolloutDuration: "0"
    spec:
      containerConcurrency: 50
      timeoutSeconds: 300
      containers:
      - name: frontend
        image: datnxdevops/knative-frontend:knative
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
