apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: identity-service
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        serving.knative.dev/rolloutDuration: "0"
    spec:
      containers:
        - name: identity-service
          image: datnxdevops/knative-identity:latest
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: REDIS_HOST
              value: redis
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: javatechie
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: root
            - name: SPRING_APPLICATION_NAME
              value: IDENTITY-SERVICE
            - name: SERVER_PORT
              value: "9898"
          ports:
            - containerPort: 9898
