# Order Service Knative Configuration
# This service handles order processing and management
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: order-service
  namespace: lab
spec:
  template:
    metadata:
      annotations:
        # Autoscaling configuration
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        # Traffic management
        serving.knative.dev/rolloutDuration: "0"
    spec:
      containerConcurrency: 50
      timeoutSeconds: 300
      containers:
      - image: datnxdevops/knative-order:latest
        ports:
        - containerPort: 8081
        env:
        # Kafka configuration - for event streaming and message queuing
        - name: KAFKA_HOST
          value: "kafka"
        - name: KAFKA_PORT
          value: "9092"
        # Database configuration - connects to MySQL stateful service
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: "javatechie"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "root"
        # Service discovery - using short DNS names for inter-service communication
        - name: URL_IDENTITY_SERVICE
          value: "http://identity-service:9898"
        - name: URL_PRODUCT_SERVICE
          value: "http://product-service:8082"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m" 