apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
      - name: identity-service
        image: datnxdevops/knative-identity:latest
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: REDIS_HOST
          value: redis
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: javatechie
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: root
        - name: SPRING_APPLICATION_NAME
          value: IDENTITY-SERVICE
        - name: SERVER_PORT
          value: "9898"
        ports:
        - containerPort: 9898

---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  selector:
    app: identity-service
  ports:
    - protocol: TCP
      port: 9898
      targetPort: 9898
